[package]
name = "comp-engine"
version = "0.1.0"
authors = ["Ben White-Horne <kneasle@gmail.com>"]
edition = "2018"

[dependencies]
proj_core = { path = "../jigsaw/core/", features = ["simd_row"] }
itertools = "0.10"

[profile.dev]
opt-level = 3

[profile.release]
# debug = true
