[workspace]
members = [
    "engine"
]

# Use optimisations even on debug builds - compilation is fast and the unoptimised code is
# SLLLLOOOOOOOW
[profile.dev]
opt-level = 3

[profile.release]
debug = true
