[package]
name = "monument"
version = "0.1.0"
authors = ["Ben White-Horne <kneasle@gmail.com>"]
edition = "2018"

[dependencies]
proj_core = { path = "../jigsaw/core/", features = ["serde"] }
itertools = "0.10"
separator = "0.4"
serde = "1.0"
serde_derive = "1.0"
toml = "0.5"
hmap = "0.1"
