[package]
name = "monument_search"
version = "0.1.0"
edition = "2018"

[dependencies]
bellframe.path = "../../bellframe/"
bit-vec = "0.6"
index_vec = "0.1"
itertools = "0.10"
log = "0.3"
monument_graph.path = "../graph/"
monument_utils.path = "../utils/"
