[package]
name = "engine"
version = "0.1.0"
authors = ["Ben White-Horne <kneasle@gmail.com>"]
edition = "2018"

[dependencies]
bellframe = { path = "../../bellframe/", features = ["serde"] }
itertools = "0.10"
shortlist = "0.1"

[dev-dependencies]
proptest = "1.0"
