[package]
name = "comp-engine"
version = "0.1.0"
authors = ["Ben White-Horne <kneasle@gmail.com>"]
edition = "2018"

[dependencies]
proj_core = { path = "../../jigsaw/core/" }
itertools = "0.10"
safe_arch = "0.5"
