[package]
name = "simd_row"
version = "0.1.0"
authors = ["Ben White-Horne <kneasle@gmail.com>"]
edition = "2018"

[dependencies]
safe_arch = "0.5"
itertools = "0.10"
proj_core = { path = "../../jigsaw/core/" }
