length = { min = 0, max = 300 }
num_comps = 30
base_calls = "near"
methods = [
    { title = "Norwich Surprise Minor" },
    { title = "Ipswich Surprise Minor" },
    { title = "Dunwich Bob Minor" },
]
course_heads = ["1xxxx6"]

[[music]]
run_lengths = [4, 5, 6]

[[music]]
patterns = ["*56"]

[[music]]
patterns = ["135246", "342516", "142536"] # Queens, exploded tittums and tittums
weight = 4
