length = "practice"
num_comps = 30
base_calls = "near"
methods = ["Norwich Surprise Minor", "Ipswich Surprise Minor", "Dunwich Bob Minor"]
method_count.min = 3

[[music]]
run_lengths = [4, 5, 6]

[[music]]
patterns = ["*56"]

[[music]]
patterns = ["135246", "342516", "142536"] # Queens, exploded tittums and tittums
weight = 4
