length = "peal"
num_comps = 50
methods = [
    "Bristol Surprise Royal",
    "Triton Delight Royal",
]
splice_style = "calls"
part_head = "165432"
music_file = "music-10.toml"

bob_weight = -4
single_weight = -5
