length = "peal"
num_comps = 40
base_calls = "near"
method = "Bristol Surprise Maximus"

[[music]]
run_lengths = [4, 5, 6, 7, 8]

# Boost scores of LB5s in order to make Monument generate more of them (this and nerfing 67890s will
# make Monument prefer LB5 courses over just keeping the 6 at home for ages).
[[music]]
patterns = ["*65432", "*23456", "23456*", "65432*"]
weight = 2
