length = "peal"
methods = [
    "Bristol Surprise Maximus",
    "Zanussi Surprise Maximus",
]
splice_style = "calls"
music_file = "music-12.toml"

# Punish calls more because Maximus generates too much music
bob_weight = -10
single_weight = -15
