length = "qp"
num_comps = 15
base_calls = "near"

[method]
stage = 8
place_notation = "x38x14x1258x36x14x58x16x78,12"

[[music]]
run_lengths = [4, 5, 6, 7]

[[music]]
patterns = ["*5678", "*8765", "5678*", "8765*", "*6578"]

# This data is only used by the test/benchmark runner and will be ignored by Monument
[test_data]
runtime_estimate = 0.043 # seconds
results = [
    { length = 1282, score = 382252089344, call_string = "HHBHBMWWMsW", ranking_score = 298168556 },
    { length = 1280, score = 382252089344, call_string = "HHMsWsHBHWHBHBH", ranking_score = 298634444 },
    { length = 1280, score = 382252089344, call_string = "HHBMBMHBH", ranking_score = 298634444 },
    { length = 1280, score = 386547056640, call_string = "BWBBHWHHH", ranking_score = 301989888 },
    { length = 1280, score = 386547056640, call_string = "HHBsHsMWHWsHBsHBH", ranking_score = 301989888 },
    { length = 1280, score = 386547056640, call_string = "BsHBsHBMWHMWWHW", ranking_score = 301989888 },
    { length = 1344, score = 408021893120, call_string = "MHMMWHMWWHW", ranking_score = 303587718 },
    { length = 1344, score = 408021893120, call_string = "HWHMHsMWsHWHH", ranking_score = 303587718 },
    { length = 1280, score = 390842023936, call_string = "HHBMHBBMH", ranking_score = 305345331 },
    { length = 1280, score = 390842023936, call_string = "HWBMHHBHBH", ranking_score = 305345331 },
    { length = 1280, score = 395136991232, call_string = "BHBHBMWHMWWHW", ranking_score = 308700774 },
    { length = 1280, score = 395136991232, call_string = "BBBMHWHHH", ranking_score = 308700774 },
    { length = 1280, score = 399431958528, call_string = "MBWHsMsWHHBHBH", ranking_score = 312056217 },
    { length = 1344, score = 420906795008, call_string = "HWHsMsWHsWsHMWHH", ranking_score = 313174698 },
    { length = 1344, score = 420906795008, call_string = "HWHsMsHsMWsHWHH", ranking_score = 313174698 },
]
