length = "QP"
methods = [
    "Yorkshire Surprise Major",
    "Superlative Surprise Major",
    "Cambridge Surprise Major",
    "Bristol Surprise Major",
    "London Surprise Major",
    { title = "Lessness Surprise Major", shorthand = "E" },
    { title = "Cornwall Surprise Major", shorthand = "W" },
    # "Deva Surprise Major",
]
part_head = "124365"
method_count = { min = 100, max = 250 }
music_file = "music-8.toml"
