length = "qp"
num_comps = 20
base_calls = "near"

[method]
place_notation = "x56x14x56x38x14x58x14x58,18"
stage = 8

[[music]]
run_length = 4

# This data is only used by the test/benchmark runner and will be ignored by Monument
[test_data]
runtime_estimate = 13.57 # seconds
results = [
    { length = 1344, score = 395136991232, call_string = "sHsMsMsWHsHBsHBHsWHBHMWsH", ranking_score = 294000737 },
    { length = 1344, score = 395136991232, call_string = "<MsWsHBHMWsWHWsWHHBHH>", ranking_score = 294000737 },
    { length = 1344, score = 395136991232, call_string = "<sHsMsWWsHHBHMWsWHsHBHH>", ranking_score = 294000737 },
    { length = 1344, score = 395136991232, call_string = "<MsWsHBHsMWsWHWsWHsHBHH>", ranking_score = 294000737 },
    { length = 1344, score = 395136991232, call_string = "sHsMWHBHsHBHBsHsWHBHMWsH", ranking_score = 294000737 },
    { length = 1344, score = 395136991232, call_string = "sHsMWsWHBHBsHBHsWHBHMWsH", ranking_score = 294000737 },
    { length = 1344, score = 395136991232, call_string = "sHsMWHBHsHBsHBHsWHBHMWsH", ranking_score = 294000737 },
    { length = 1344, score = 395136991232, call_string = "sHsMsMsWHsHBHBsHsWHBHMWsH", ranking_score = 294000737 },
    { length = 1312, score = 386547056640, call_string = "sHsMsMsWHsHBsHBHsHHBWsH", ranking_score = 294624280 },
    { length = 1312, score = 386547056640, call_string = "sWsHHsHBsHBHsWsHBsHMWsH", ranking_score = 294624280 },
    { length = 1312, score = 386547056640, call_string = "<MWsWHMBsHBWsWHsHBHH>", ranking_score = 294624280 },
    { length = 1312, score = 386547056640, call_string = "<sHsMWBHMWHWHHBHH>", ranking_score = 294624280 },
    { length = 1312, score = 386547056640, call_string = "sHsMWHBHsHBsHBHsHHBWsH", ranking_score = 294624280 },
    { length = 1312, score = 386547056640, call_string = "sWsHHsHBHBsHsWsHBsHMWsH", ranking_score = 294624280 },
    { length = 1280, score = 377957122048, call_string = "<HBsHBHBHHHBsHBHBHH>", ranking_score = 295279001 },
    { length = 1280, score = 377957122048, call_string = "sWsHHsHBHsHHBsHBWsH", ranking_score = 295279001 },
    { length = 1280, score = 377957122048, call_string = "<HBsHBHBHHHBHBsHBHH>", ranking_score = 295279001 },
    { length = 1312, score = 395136991232, call_string = "sWsHHsHBHBsHsWHBHMWsH", ranking_score = 301171487 },
    { length = 1312, score = 395136991232, call_string = "sWsHHsHBsHBHsWHBHMWsH", ranking_score = 301171487 },
    { length = 1280, score = 386547056640, call_string = "sWsHHsHBsHBHsHHBWsH", ranking_score = 301989888 },
]
