length = "practice"
num_comps = 30
base_calls = "near"
methods = [
    "Cambridge Surprise Minor",
    "London Surprise Minor",
    # "Primrose Surprise Minor",
    # "Bourne Surprise Minor",
    # "Ipswich Surprise Minor",
]
end_indices = [21] # Only allow finishing at the handstroke snap

[[music]]
run_lengths = [4, 5, 6]

[[music]]
patterns = ["*56"]

# Queens, exploded tittums and tittums are worth 4
[[music]]
patterns = ["135246", "342516", "142536"]
weight = 4
