length = "QP"
num_comps = 30
base_calls = "near"

[method]
place_notation = "-38-14-56-16-12-58-14-58,12"
stage = 8

[[music]]
run_length = 4

[[music]]
patterns = [ "*6578", "*5678", "*8765", "5678*", "8765*" ]
