length = "QP"
num_comps = 20
methods = [
    "Yorkshire Surprise Major",
    "Bristol Surprise Major",
    "Superlative Surprise Major",
    "Cambridge Surprise Major",
    { title = "Lessness Surprise Major", shorthand = "E" },
]
music_file = "music-8.toml"
