length = "qp"
num_comps = 15
base_calls = "near"
course_heads = ["1xxxxx78", "1xxx7856", "1xxx8765", "13456782", "18234567"]

[method]
stage = 8
place_notation = "-38-14-1256-18-3478-58-16-78,12"

[[music]]
run_lengths = [4, 5, 6, 7]

[[music]]
patterns = ["*5678", "*8765", "5678*", "8765*", "*6578"]

# This data is only used by the test/benchmark runner and will be ignored by Monument
[test_data]
runtime_estimate = 23 # seconds
