length = "qp"
num_comps = 15
course_heads = ["1xxxxx78", "1xxx7856", "1xxx8765", "13456782", "18234567"]
method = "Romanby Green Delight Major"

[[music]]
run_lengths = [4, 5, 6, 7]

[[music]]
patterns = ["*5678", "*8765", "5678*", "8765*", "*6578"]
