length = "practice"
num_comps = 20
base_calls = "none"
methods = [
    "Bristol Surprise Royal",
    # "Yorkshire Surprise Royal",
    # "Kenninghall Surprise Royal",
    "Warstone Surprise Royal",
    # "Triton Delight Royal",
    # "Sgurr A'Chaorachain Surprise Royal",
    # { stage = 10, place_notation = "-30-14.50-12.30.14-70.38.16-16.70-16-10,12", name = "Funky Boi", shorthand = "F" }
]
splice_style = "calls"
# part_head = "165432"

bob_weight = -4
single_weight = -6

# method_count = { min = 900, max = 1200 }
# method_count = { min = 500, max = 700 }
method_count.max = 400

[[music]]
run_lengths = [4, 5, 6, 7, 8]

# Counting 67890s as 5-bell runs tends to make Monument generate very static compositions, leaving 6
# unaffected for as long as possible.  So we nerf 67890s to encourage it to generate more
# interesting comps
[[music]]
patterns = ["09876*", "*67890"]
weight = -0.8

# Boost scores of LB5s in order to make Monument generate more of them (this and nerfing 67890s will
# make Monument prefer LB5 courses over just keeping the 6 at home for ages).
[[music]]
patterns = ["*65432", "*23456", "23456*", "65432*"]
weight = 1
