length = "practice"
num_comps = 20
base_calls = "none"
methods = [
    "Bristol Surprise Royal",
    # "Yorkshire Surprise Royal",
    # "Kenninghall Surprise Royal",
    "Warstone Surprise Royal",
    # "Triton Delight Royal",
    # "Sgurr A'Chaorachain Surprise Royal",
    # { stage = 10, place_notation = "-30-14.50-12.30.14-70.38.16-16.70-16-10,12", name = "Funky Boi", shorthand = "F" }
]
splice_style = "calls"
# part_head = "165432"
music_file = "music-10.toml"

bob_weight = -4
single_weight = -6

# method_count = { min = 900, max = 1200 }
# method_count = { min = 500, max = 700 }
method_count.max = 400
