length = "QP"
base_calls = "near"
start_indices = [0]
method = "Superlative Surprise Major"

[[music]]
run_lengths = [4, 5, 6, 7]

[[music]]
patterns = [ "*6578", "*5678", "*8765", "5678*", "8765*" ]
