length = "QP"
base_calls = "near"
start_indices = [0]

[method]
place_notation = "x36x14x58x36x14x58x36x78,12"
stage = 8

[[music]]
run_lengths = [4, 5, 6, 7]

[[music]]
patterns = [ "*6578", "*5678", "*8765", "5678*", "8765*" ]

# This data is only used by the test/benchmark runner and will be ignored by Monument
[test_data]
runtime_estimate = 0.043 # seconds
results = [
    { length = 1280, score = 601295421440, call_string = "HBMMBMHBH", ranking_score = 469762048 },
    { length = 1280, score = 601295421440, call_string = "HBMMBsMsHBH", ranking_score = 469762048 },
    { length = 1280, score = 601295421440, call_string = "HHBMBsHsMBH", ranking_score = 469762048 },
    { length = 1280, score = 601295421440, call_string = "WHBHMsMsHBHBsHsH", ranking_score = 469762048 },
    { length = 1344, score = 635655159808, call_string = "MsWsHWMsMMsWsHMsW", ranking_score = 472957708 },
    { length = 1280, score = 605590388736, call_string = "BMMBsHsMWWB", ranking_score = 473117491 },
    { length = 1280, score = 605590388736, call_string = "WHWBMHBHWB", ranking_score = 473117491 },
    { length = 1280, score = 609885356032, call_string = "HBMBsHsMBHH", ranking_score = 476472934 },
    { length = 1280, score = 609885356032, call_string = "MHMBMsMsHBHB", ranking_score = 476472934 },
    { length = 1250, score = 597000454144, call_string = "BMMsMsWsHsMsMsWsH>", ranking_score = 477600363 },
    { length = 1250, score = 597000454144, call_string = "sHBsMsMsWsHsMWsMsWsH>", ranking_score = 477600363 },
    { length = 1250, score = 597000454144, call_string = "MWsMsWBHsMsWHMsM>", ranking_score = 477600363 },
    { length = 1280, score = 614180323328, call_string = "WHBHHBHWWB", ranking_score = 479828377 },
    { length = 1280, score = 614180323328, call_string = "MWHMWBMsMsHBHB", ranking_score = 479828377 },
    { length = 1344, score = 648540061696, call_string = "sMsWHMsMMsWMWsHsH", ranking_score = 482544688 },
    { length = 1280, score = 618475290624, call_string = "WHWBMMsWsHBB", ranking_score = 483183820 },
    { length = 1344, score = 652835028992, call_string = "MsWHsWMsMMsWMW", ranking_score = 485740348 },
    { length = 1280, score = 622770257920, call_string = "WHWBMBsHsMWB", ranking_score = 486539264 },
    { length = 1280, score = 622770257920, call_string = "sHBsMMsWsHBsWBsH", ranking_score = 486539264 },
    { length = 1280, score = 622770257920, call_string = "BsMMsWsHBsWBsHsH", ranking_score = 486539264 },
    { length = 1250, score = 609885356032, call_string = "sHBsMHMHsHsMsH>", ranking_score = 487908284 },
    { length = 1280, score = 627065225216, call_string = "sHBsMBsHsMWsWBsH", ranking_score = 489894707 },
    { length = 1280, score = 631360192512, call_string = "BMMMsWsHBWB", ranking_score = 493250150 },
    { length = 1280, score = 635655159808, call_string = "BsMBsHsMsWWWB", ranking_score = 496605593 },
    { length = 1280, score = 652835028992, call_string = "HBMMBsHsMBH", ranking_score = 510027366 },
    { length = 1280, score = 652835028992, call_string = "BMMsMsWBsMsWB", ranking_score = 510027366 },
    { length = 1280, score = 652835028992, call_string = "WHWBMsMsHBHB", ranking_score = 510027366 },
    { length = 1250, score = 644245094400, call_string = "MHMBMsMM>", ranking_score = 515396075 },
    { length = 1250, score = 648540061696, call_string = "MWHMWBMsMM>", ranking_score = 518832049 },
    { length = 1280, score = 682899800064, call_string = "BMMsMsWsHBsWB", ranking_score = 533515468 },
]
