length = "qp"
num_comps = 40
base_calls = "near"
method = "Yorkshire Surprise Major"

course_heads = ["xxxxxx78", "xxxx8765", "xxxx7856"]


[[music]]
run_lengths = [4, 5, 6, 7]

[[music]]
patterns = ["*6578", "*5678", "*8765", "5678*", "8765*"]
weight = 6
