length = "QP"
base_calls = "near"
method.title = "Yorkshire Surprise Major"

[[music]]
run_lengths = [4, 5, 6, 7]
# weight defaults to 1.0

[[music]]
patterns = ["*5678", "*8765", "5678*", "8765*", "*6578"]
weight = 0.5
