length = "QP"
num_comps = 20
base_calls = "near"
method.title = "Yorkshire Surprise Major"

[[music]]
run_length = 4

[[music]]
patterns = ["*6578", "*5678", "*8765", "5678*", "8765*"]

# This data is only used by the test/benchmark runner and will be ignored by Monument
[test_data]
runtime_estimate = 0.123 # seconds
results = [
    { length = 1312, score = 403726925824, call_string = "BBsHBBHBsHMMsHsH", ranking_score = 307718693 },
    { length = 1280, score = 395136991232, call_string = "sHsWsHBsHsMsMsHBHBsH", ranking_score = 308700774 },
    { length = 1280, score = 395136991232, call_string = "sHsWBsHsMBBMsWsH", ranking_score = 308700774 },
    { length = 1280, score = 395136991232, call_string = "sHsWBsMsHsHBHBsH", ranking_score = 308700774 },
    { length = 1280, score = 395136991232, call_string = "BBsWsHBsHMHsMWsHsH", ranking_score = 308700774 },
    { length = 1280, score = 395136991232, call_string = "BBsWHBHsMsHsMWsHsH", ranking_score = 308700774 },
    { length = 1280, score = 395136991232, call_string = "BsHBsMsWsHBsHsHWsHsH", ranking_score = 308700774 },
    { length = 1280, score = 395136991232, call_string = "BBsWsHBWsHsWsWsH", ranking_score = 308700774 },
    { length = 1280, score = 399431958528, call_string = "sHMWBBHBHMMsH", ranking_score = 312056217 },
    { length = 1280, score = 399431958528, call_string = "WHBsHMBsHBWsHsH", ranking_score = 312056217 },
    { length = 1280, score = 399431958528, call_string = "sHsWHBHsMsMHBsHBsH", ranking_score = 312056217 },
    { length = 1280, score = 403726925824, call_string = "sHsMsMsWHBHsHBHBsH", ranking_score = 315411660 },
    { length = 1280, score = 403726925824, call_string = "sHBsHBWsHBsHHsMsH", ranking_score = 315411660 },
    { length = 1280, score = 403726925824, call_string = "BBsWsHBsHsMsHsMWsHsH", ranking_score = 315411660 },
    { length = 1312, score = 416611827712, call_string = "sHBBsHBBsHBsHHsMsH", ranking_score = 317539502 },
    { length = 1280, score = 408021893120, call_string = "sHsWHBHBsWBsHMsWsH", ranking_score = 318767104 },
    { length = 1280, score = 412316860416, call_string = "BBsWsHBsHsHWsHsH", ranking_score = 322122547 },
    { length = 1280, score = 412316860416, call_string = "sHsWHBHsMsMsHBHBsH", ranking_score = 322122547 },
    { length = 1280, score = 425201762304, call_string = "sHsMWsHBBsHBHHsMsH", ranking_score = 332188876 },
    { length = 1280, score = 425201762304, call_string = "sHsWHHBsHBBsHMsWsH", ranking_score = 332188876 },
]
