length = "QP"
# length = { min = 0, max = 400 }
num_comps = 16
base_calls = "near"
method = "Yorkshire Surprise Royal"

[[calls]]
symbol = "x"
place_notation = "16"

[[music]]
run_lengths = [4, 5, 6]
