length = "QP"
# length = { min = 0, max = 400 }
num_comps = 16
base_calls = "near"

[method]
stage = "Royal"
place_notation = "x30x14x50x16x1270x38x14x50x16x90,12"

[[calls]]
symbol = "x"
place_notation = "16"

[[music]]
run_lengths = [4, 5, 6]

# This data is only used by the test/benchmark runner and will be ignored by Monument
[test_data]
runtime_estimate = 0.0098 # seconds
results = [
    { length = 1280, score = 755914244096, call_string = "5:sHsWHsMsWxBWxH", ranking_score = 590558003 },
    { length = 1280, score = 755914244096, call_string = "5:sHsWHsMWxBsWxH", ranking_score = 590558003 },
    { length = 1280, score = 755914244096, call_string = "5:MxBWsHsMWxHxH", ranking_score = 590558003 },
    { length = 1280, score = 755914244096, call_string = "5:WWxHxBW", ranking_score = 590558003 },
    { length = 1280, score = 760209211392, call_string = "5:xHsWxBsWsWsH", ranking_score = 593913446 },
    { length = 1280, score = 764504178688, call_string = "5:HWHMWxBWH", ranking_score = 597268889 },
    { length = 1280, score = 764504178688, call_string = "5:sHWxBsWMsWsH", ranking_score = 597268889 },
    { length = 1280, score = 764504178688, call_string = "5:sHsWxBWsHMWsH", ranking_score = 597268889 },
    { length = 1280, score = 764504178688, call_string = "5:HWHMWxBsMsWxH", ranking_score = 597268889 },
    { length = 1280, score = 768799145984, call_string = "5:sHsWxBxHsWsH", ranking_score = 600624332 },
    { length = 1280, score = 773094113280, call_string = "5:MHsMsWHWxBxH", ranking_score = 603979776 },
    { length = 1280, score = 785979015168, call_string = "5:sHsWHMWxBsMsWxH", ranking_score = 614046105 },
    { length = 1280, score = 785979015168, call_string = "5:sHsWsWxBsMxH", ranking_score = 614046105 },
    { length = 1280, score = 794568949760, call_string = "5:MHWxBMHW", ranking_score = 620756992 },
    { length = 1280, score = 803158884352, call_string = "5:MxBWsHsWsWsH", ranking_score = 627467878 },
    { length = 1280, score = 811748818944, call_string = "5:sHsWxBWMsWsH", ranking_score = 634178764 },
]
