length = "QP"
num_comps = 30
base_calls = "near"

[method]
place_notation = "x36x14x58x36x14x58x36x78,12"
stage = 8

[[music]]
run_length = 4

[[music]]
patterns = [ "*6578", "*5678", "*8765", "5678*", "8765*" ]
