length = "QP"
num_comps = 30
base_calls = "near"

[method]
place_notation = "x36x14x58x36x14x58x36x78,12"
stage = 8

[[music]]
run_lengths = [4, 5, 6, 7]

[[music]]
patterns = [ "*6578", "*5678", "*8765", "5678*", "8765*" ]

# This data is only used by the test/benchmark runner and will be ignored by Monument
[test_data]
runtime_estimate = 0.8 # seconds
results = [
    { length = 1250, score = 142, call_string = "5:sHBsMHMHsHsMsH", ranking_score = 0.1136 },
    { length = 1342, score = 153, call_string = "7:sMMsMMsWsHsMsHWsH", ranking_score = 0.11400894 },
    { length = 1342, score = 153, call_string = "7:sMMsWHMWMMsWMW", ranking_score = 0.11400894 },
    { length = 1280, score = 146, call_string = "5:sHBsMBsHsMWsWBsH", ranking_score = 0.1140625 },
    { length = 1278, score = 146, call_string = "7:sMsMsWMWsHBBsHsMWBsH", ranking_score = 0.114241004 },
    { length = 1278, score = 146, call_string = "7:sMsMsWBHBsMWsWB", ranking_score = 0.114241004 },
    { length = 1280, score = 147, call_string = "5:BMMMsWsHBWB", ranking_score = 0.11484375 },
    { length = 1280, score = 147, call_string = "7:sMMsMMsWBBHBsH", ranking_score = 0.11484375 },
    { length = 1342, score = 155, call_string = "7:sMMsMsWsWMsWMW", ranking_score = 0.11549926 },
    { length = 1342, score = 155, call_string = "7:sMMsWsWsMMsWMW", ranking_score = 0.11549926 },
    { length = 1342, score = 155, call_string = "7:sMMsMMsHMWMWH", ranking_score = 0.11549926 },
    { length = 1342, score = 155, call_string = "7:sMsWsWMsMMsWMW", ranking_score = 0.11549926 },
    { length = 1342, score = 155, call_string = "7:sMMsMMsWsHsHMW", ranking_score = 0.11549926 },
    { length = 1280, score = 148, call_string = "5:BsMBsHsMsWWWB", ranking_score = 0.115625 },
    { length = 1344, score = 156, call_string = "7:sMMsMMsWsWsHsH", ranking_score = 0.116071425 },
    { length = 1344, score = 157, call_string = "7:sMMsMMsWsMsHsMsWsH", ranking_score = 0.11681548 },
    { length = 1278, score = 150, call_string = "7:sMsMsWMWsHBsMHBsHBsH", ranking_score = 0.11737089 },
    { length = 1278, score = 150, call_string = "7:sMMHBsHBBMsWMW", ranking_score = 0.11737089 },
    { length = 1280, score = 152, call_string = "5:WHWBMsMsHBHB", ranking_score = 0.11875 },
    { length = 1280, score = 152, call_string = "5:HBMMBsHsMBH", ranking_score = 0.11875 },
    { length = 1280, score = 152, call_string = "5:BMMsMsWBsMsWB", ranking_score = 0.11875 },
    { length = 1250, score = 150, call_string = "5:MHMBMsMM", ranking_score = 0.12 },
    { length = 1250, score = 151, call_string = "5:MWHMWBMsMM", ranking_score = 0.1208 },
    { length = 1344, score = 163, call_string = "7:sMMsMMsWsHsMsMsWsH", ranking_score = 0.12127976 },
    { length = 1342, score = 163, call_string = "7:sMMsMMsWsHMsWsHsH", ranking_score = 0.121460505 },
    { length = 1280, score = 159, call_string = "5:BMMsMsWsHBsWB", ranking_score = 0.12421875 },
    { length = 1342, score = 169, call_string = "7:sMMsMMsWMWsHsH", ranking_score = 0.12593144 },
    { length = 1344, score = 176, call_string = "7:MMsMMMsM", ranking_score = 0.13095239 },
    { length = 1344, score = 176, call_string = "7:MsMMMsMM", ranking_score = 0.13095239 },
    { length = 1344, score = 176, call_string = "7:sMMMsMMM", ranking_score = 0.13095239 },
]
