length = "QP"
num_comps = 20
base_calls = "near"

[method]
place_notation = "x38x14x58x16x12x38x14x78,12"
stage = 8

[[music]]
run_length = 4

[[music]]
patterns = [ "*6578", "*5678", "*8765", "5678*", "8765*" ]
