length = "QP"
num_comps = 20
base_calls = "near"

[method]
place_notation = "x38x14x58x16x12x38x14x78,12"
stage = 8

[[music]]
run_length = 4

[[music]]
patterns = [ "*6578", "*5678", "*8765", "5678*", "8765*" ]

# This data is only used by the test/benchmark runner and will be ignored by Monument
[test_data]
runtime_estimate = 1.1 # seconds
results = [
    { length = 1312, score = 94, call_string = "5:BBsHBBHBsHMMsHsH", ranking_score = 0.07164634 },
    { length = 1280, score = 92, call_string = "5:BBsWsHBWsHsWsWsH", ranking_score = 0.071875 },
    { length = 1280, score = 92, call_string = "5:sHsWBsMsHsHBHBsH", ranking_score = 0.071875 },
    { length = 1280, score = 92, call_string = "5:BsHBsMsWsHBsHsHWsHsH", ranking_score = 0.071875 },
    { length = 1280, score = 92, call_string = "5:BBsWHBHsMsHsMWsHsH", ranking_score = 0.071875 },
    { length = 1280, score = 92, call_string = "5:sHsWsHBsHsMsMsHBHBsH", ranking_score = 0.071875 },
    { length = 1280, score = 92, call_string = "5:sHsWBsHsMBBMsWsH", ranking_score = 0.071875 },
    { length = 1280, score = 92, call_string = "5:BBsWsHBsHMHsMWsHsH", ranking_score = 0.071875 },
    { length = 1280, score = 93, call_string = "5:sHsWHBHsMsMHBsHBsH", ranking_score = 0.07265625 },
    { length = 1280, score = 93, call_string = "5:sHMWBBHBHMMsH", ranking_score = 0.07265625 },
    { length = 1280, score = 93, call_string = "5:WHBsHMBsHBWsHsH", ranking_score = 0.07265625 },
    { length = 1280, score = 94, call_string = "5:sHsMsMsWHBHsHBHBsH", ranking_score = 0.0734375 },
    { length = 1280, score = 94, call_string = "5:sHBsHBWsHBsHHsMsH", ranking_score = 0.0734375 },
    { length = 1280, score = 94, call_string = "5:BBsWsHBsHsMsHsMWsHsH", ranking_score = 0.0734375 },
    { length = 1312, score = 97, call_string = "5:sHBBsHBBsHBsHHsMsH", ranking_score = 0.07393292 },
    { length = 1280, score = 95, call_string = "5:sHsWHBHBsWBsHMsWsH", ranking_score = 0.07421875 },
    { length = 1280, score = 96, call_string = "5:BBsWsHBsHsHWsHsH", ranking_score = 0.075 },
    { length = 1280, score = 96, call_string = "5:sHsWHBHsMsMsHBHBsH", ranking_score = 0.075 },
    { length = 1280, score = 99, call_string = "5:sHsWHHBsHBBsHMsWsH", ranking_score = 0.07734375 },
    { length = 1280, score = 99, call_string = "5:sHsMWsHBBsHBHHsMsH", ranking_score = 0.07734375 },
]
