length = "QP"
num_comps = 16
base_calls = "near"

[method]
stage = "Royal"
place_notation = "x30x14x50x16x1270x38x14x50x16x90,12"

[[calls]]
symbol = "x"
place_notation = "16"

[[music]]
run_length = 4
